# -*- coding: utf-8 -*-
"""ML Project - ARM(pt2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17WLNnybQRDkCJ36_MgtRQARBM8FHAljk
"""

install.packages("arules")
install.packages("TSP")
install.packages("data.table")
install.packages("arulesViz", dependencies = TRUE)
install.packages("sp")
install.packages("dplyr", dependencies = TRUE)
install.packages("purrr", dependencies = TRUE)
install.packages("devtools", dependencies = TRUE)
install.packages("tidyr")

library(viridis)
library(arules)
library(TSP)
library(data.table)
library(tcltk)
library(dplyr)
library(devtools)
library(purrr)
library(tidyr)
library(arulesViz)

library(arulesViz)

lifeExpectancyARM <- read.transactions("/content/lifeExpectancyARM.csv",
                           rm.duplicates = FALSE,
                           format = "basket",
                           sep=",",
                           )
inspect(lifeExpectancyARM)

##### Use apriori to get the RULES
FrulesK = arules::apriori(lifeExpectancyARM, parameter = list(support=.35,
                                                 confidence=.5, minlen=2))
inspect(FrulesK)

## Sort rules by a measure such as conf, sup, or lift
SortedRulesK <- sort(FrulesK, by="support", decreasing=TRUE)
inspect(SortedRulesK[1:15])

## Sort rules by a measure such as conf, sup, or lift
SortedRulesK <- sort(FrulesK, by="confidence", decreasing=TRUE)
inspect(SortedRulesK[1:15])

## Sort rules by a measure such as conf, sup, or lift
SortedRulesK <- sort(FrulesK, by="lift", decreasing=TRUE)
inspect(SortedRulesK[1:15])

## Associations with Countries with negative Life expectancy change
NegativeLEChangeRules <- apriori(data=lifeExpectancyARM,parameter = list(supp=.001, conf=.01, minlen=2),
                       appearance = list(default="rhs", lhs="Negative Change"),
                       control=list(verbose=FALSE))
NegativeLEChangeRules <- sort(NegativeLEChangeRules, decreasing=TRUE, by="lift")
inspect(NegativeLEChangeRules[1:10])

## Associations with Countries with Low Life expectancy increase
LowLEChangeRules <- apriori(data=lifeExpectancyARM,parameter = list(supp=.001, conf=.01, minlen=2),
                       appearance = list(default="rhs", lhs="Low Change"),
                       control=list(verbose=FALSE))
LowLEChangeRules <- sort(LowLEChangeRules, decreasing=TRUE, by="lift")
inspect(LowLEChangeRules[1:10])

## Associations with Countries with Moderate Life expectancy increase
ModerateLEChangeRules <- apriori(data=lifeExpectancyARM,parameter = list(supp=.001, conf=.01, minlen=2),
                       appearance = list(default="rhs", lhs="Moderate Change"),
                       control=list(verbose=FALSE))
ModerateLEChangeRules <- sort(ModerateLEChangeRules, decreasing=TRUE, by="lift")
inspect(ModerateLEChangeRules[1:10])

## Associations with Countries with High Life expectancy increase
HighLEChangeRules <- apriori(data=lifeExpectancyARM,parameter = list(supp=.001, conf=.01, minlen=2),
                       appearance = list(default="rhs", lhs="High Change"),
                       control=list(verbose=FALSE))
HighLEChangeRules <- sort(HighLEChangeRules, decreasing=TRUE, by="lift")
inspect(HighLEChangeRules[1:10])

plot(HighLEChangeRules, method = "graph",
     measure = "confidence", shading = "lift")

plot(LowLEChangeRules, method = "graph",
     measure = "confidence", shading = "lift")

